### ISSUE TITLE
Run SymbolServer

### ISSUE THREAD

**Issue by triaxia** [SymbolSource/SymbolSource#1]
I just tried symbol server... 

all compiled 
run SymbolSource.Server either with IIS Express or IIS
nuget.exe push Test.2.19.5.nupkg -Source "http://localhost:57738/" -ApiKey "MyKey"
your package pushed
nuget.exe list -prerelease -Source "http://localhost:57738/"
No packages found

Any idea why?

I can see files created in the directory specified in FileStorage.RootPath settings

Thanks

**Comment by TripleEmcoder** [comment]
To diagnose you might want to run:
```
nuget list -prerelease -allversions -source https://nuget.smbsrc.net/,all,new
```

And try replacing new with other statuses to find where the package got stuck:
- `new `– not yet opened, random package name and unknown version,
- `original `– a copy of the uploaded package, without any processing, useful if we improve the indexer and need to resubmit packages without any users’ actions,
- `indexingqueued `– indexing will soon start asynchronously,
- `indexing `– processing is in progress as you are looking at the list,
- `succeeded `– the package has been indexed without any issues,
- `deletingqueued `– deleting with soon start asynchronously,
- `deleting `– deleting is in progress as you are looking at the list,
- `deleted `– the package has been completely removed from the index,
- `partial `– something went wrong, either during indexing or deleting, and some symbols and sources might be available, but some may not,
- `damagednew `– package could not be read with a standard NuGet library,
- `damagedindexing`, `damageddeleting `– these will probably indicate an error in SymbolSource.

Please also post console output from the Processor and what files you see under RootPath (`dir /s` or similar).

**Comment by triaxia** [comment]
Thanks for your response.

output of nuget push and list
--------------------------------------
C:\Users\pxgu\Desktop\Klondike\Files>D:\ccviews\QR\QS\Tools\nuget.exe push Test.2.19.5.symbols.nupkg -Source "http://localhost:57738/" -ApiKey "QrKey" 
Pushing Test.2.19.5.symbols.nupkg to 'http://localhost:57738/'...
  PUT http://localhost:57738/api/v2/package/
  OK http://localhost:57738/api/v2/package/ 10684ms
Your package was pushed.

C:\Users\pxgu\Desktop\Klondike\Files>D:\ccviews\QR\QS\Tools\nuget.exe list -prerelease -allversion -Source "http://localhost:57738/,all,new"  
0f1acf92-8074-4a56-9c71-1373242bc606 1.0.0-unknown
1f3afe6c-49dd-4f43-aaf0-52b1e39b033c 1.0.0-unknown

output of dir /s
-----------------------------------
 Volume in drive D is Data
 Volume Serial Number is CE55-39B5

 Directory of D:\Test\XX

26/03/2018  10:27 AM    <DIR>          .
26/03/2018  10:27 AM    <DIR>          ..
26/03/2018  10:27 AM                 0 1.log
26/03/2018  10:18 AM               207 4d715a03-6451-4a9d-9564-ae173f5b3c24.run
26/03/2018  10:25 AM               207 68522cdc-1a04-477d-8cc9-b436f06b15bc.run
26/03/2018  10:17 AM    <DIR>          _
               3 File(s)            414 bytes

 Directory of D:\Test\XX\_

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          .new
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:17 AM    <DIR>          .users
26/03/2018  10:25 AM    <DIR>          0
26/03/2018  10:17 AM    <DIR>          1
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          0
26/03/2018  10:17 AM    <DIR>          1
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=\0

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          0f1acf92-8074-4a56-9c71-1373242bc606
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=\0\0f1acf92-8074-4a56-9c71-1373242bc606

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          1.0-unknown
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=\0\0f1acf92-8074-4a56-9c71-1373242bc606\1.0-unknown

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM           151,940 0f1acf92-8074-4a56-9c71-1373242bc606.1.0-unknown.nupkg
               1 File(s)        151,940 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=\1

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:17 AM    <DIR>          1f3afe6c-49dd-4f43-aaf0-52b1e39b033c
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=\1\1f3afe6c-49dd-4f43-aaf0-52b1e39b033c

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:17 AM    <DIR>          1.0-unknown
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\.users\4_1-frecRypdrmi9u77yJy9FM0ge5XDDv5VfgJjxEGs=\1\1f3afe6c-49dd-4f43-aaf0-52b1e39b033c\1.0-unknown

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:17 AM           151,940 1f3afe6c-49dd-4f43-aaf0-52b1e39b033c.1.0-unknown.nupkg
               1 File(s)        151,940 bytes

 Directory of D:\Test\XX\_\.new\0

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          0f1acf92-8074-4a56-9c71-1373242bc606
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\0\0f1acf92-8074-4a56-9c71-1373242bc606

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM    <DIR>          1.0-unknown
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\0\0f1acf92-8074-4a56-9c71-1373242bc606\1.0-unknown

26/03/2018  10:25 AM    <DIR>          .
26/03/2018  10:25 AM    <DIR>          ..
26/03/2018  10:25 AM                46 0f1acf92-8074-4a56-9c71-1373242bc606.1.0-unknown.txt
               1 File(s)             46 bytes

 Directory of D:\Test\XX\_\.new\1

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:17 AM    <DIR>          1f3afe6c-49dd-4f43-aaf0-52b1e39b033c
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\1\1f3afe6c-49dd-4f43-aaf0-52b1e39b033c

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:17 AM    <DIR>          1.0-unknown
               0 File(s)              0 bytes

 Directory of D:\Test\XX\_\.new\1\1f3afe6c-49dd-4f43-aaf0-52b1e39b033c\1.0-unknown

26/03/2018  10:17 AM    <DIR>          .
26/03/2018  10:17 AM    <DIR>          ..
26/03/2018  10:17 AM                46 1f3afe6c-49dd-4f43-aaf0-52b1e39b033c.1.0-unknown.txt
               1 File(s)             46 bytes

     Total Files Listed:
               7 File(s)        304,386 bytes
              50 Dir(s)  345,245,863,936 bytes free

**Comment by triaxia** [comment]
I did not realise I have to run SymbolSource.Processor.Console to get indexing work...

Once I ran it, everything is good.

Cheers,

**Comment by TripleEmcoder** [comment]
Exactly - a package left in the new state and named with a guid indicates no processing has been run at all.

**Comment by triaxia** [comment]
I am going to fork out and implement a couple fixes.

Is that the right process to contribute?

Cheers

**Comment by TripleEmcoder** [comment]
Sure thing, pull requests are very much welcome. But if you plan to implement something bigger than fixes then please create a separate issue and describe the planned changes so that we could discuss them beforehand.
