### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by JCookVF** [SymbolSource/SymbolSource#10]
I'm getting a compile error in SymbolSource.Support.TelemetryProcessor.cs

in line 23

```
            if (item is RequestTelemetry request)
            {
                if (IsNotFound(request) && IsSymbol(request))
                {
                    request.Success = true;
                }
            }
```

I am not familiar with this syntax, and it is giving me a compile error. Is this a known issue? I am running this on .NET 4.6.2. and it seems to be having trouble with request not existing in the context. Is there something I am missing here?

**Comment by TripleEmcoder** [comment]
This is C# 7.0 pattern matching, see here: https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching

Could you by any chance be building this under something other than VS 2017?

**Comment by JCookVF** [comment]
ah, yea that would be the problem. I am using VS 2015. Thanks for the response!

**Comment by TripleEmcoder** [comment]
Glad I could help. In general I can really recommend switching to VS 2017 if that's an option for you. The improvements in C# and VS are massive.
