### ISSUE TITLE
Unable to upload symbols package

### ISSUE THREAD

**Issue by scottselberg** [SymbolSource/SymbolSource#12]
Hi,  I was trying to setup this application and running into some problems.  I'm not sure if it's my lack of ASP knowledge or a true bug.

In my situation I am pushing the regular nuget packages to an Artifactory server inside of a firewall and am trying to host the application on an instance of Windows Server 2016 running IIS.  For the app settings, I've selected:

Container.SecurityType to NullSecurityService (I defined values for "InstanceSalt" and "PushApiKeys")
Container.StorageType to LocalStorageService (I defined a vlue for FileStorage.RootPath)
Container.SchedulerType to FileSchedulerService

I can browse to the url and see the ATOM feed.  Nuget.exe list returns "No packages found".  Nuget put does the following:

nuget.exe push -Source <url> -apikey <key> <package>
Pushing <package> to '<url>'...
   PUT <url>
   MethodNotAllowed <url> 46ms
Response status code does not indicate success: 405 (Method Not Allowed)

I did see the issue with the WebDav keys and I can confirm that the following are present in my config file:
<remove name="WebDAVModule" />
<remove name="WebDAV" />

Any help you can provide would be appreciated.

**Comment by scottselberg** [comment]
This may be related to the earlier ticket with the WebDAV elements.  I played with them a bit more and now I"m getting the 500 (Internal Server Error) if they are present and the 405 if they are not present.

**Comment by scottselberg** [comment]
OK, I think I figured it out.  I was uploading to http://server/SymbolSource but I need to upload to http://server/SymbolSource/api/v2/package.  Then it works fine.

**Comment by TripleEmcoder** [comment]
Glad to see you figured it out. For the record, if you install the server with a prefix like `/SymbolSource`, then you need to provide the full endpoint URL when pushing. NuGet only appends the endpoint automatically if pushing to the root path.
