### ISSUE TITLE
Possible bug in determination of folder name based on hash

### ISSUE THREAD

**Issue by jkommeren** [SymbolSource/SymbolSource#3]
The foldername in which the pdbs are stored is partly built on the hash it generates.

However the hash it uses for the foldername is different from the hash/foldername that Visual Studio 2017 expects for debugging.

Investigated with wireshark

In my case: VisualStudio was looking for "E28DBBA883FF43D1B24CAC9F49CC74191" for a certain pdb, but SymbolSource stored it in a folder named "E28DBBA883FF43D1B24CAC9F49CC74192"

(context is IndexPackageTask.cs)
![image](https://user-images.githubusercontent.com/2786340/38878006-41df250a-4260-11e8-861a-a8e923bd247b.png)

I think just using (line 132, IndexPackageTask.cs)  

`var symbolStatus = new SymbolStatus(new SymbolName(binaryInfo.Name, binaryInfo.SymbolHash));`

instead of 

`var symbolStatus = new SymbolStatus(new SymbolName(binaryInfo.Name, binaryInfo.SymbolInfo.Hash));`

Fixes it.

I do not have the means to test this, or any clue of what I might be missing.

Could you shed your light on this?

**Comment by TripleEmcoder** [comment]
As a side note you might want to use Fiddler next time diagnosing these kind of issues, it's much more convenient than Wireshark or other generic network traffic analyzers.

Now the difference between the pieces of code that you mentioned is the following:
* `binaryInfo.SymbolHash` is the expected PDB hash as stored in the DLL,
* `binaryInfo.SymbolInfo.Hash` is the hash stored in the PDB file found by mathing it by name, as in `Path.ChangeExtension("Library.dll", ".pdb")`.

So the code is correct in storing the PDB in a folder named with the actual hash, not the one expected by DLL. If did the opposite like you suggested then Visual Studio would indeed download the file, but a hash mismatch would still be reported by the client, and symbols would not load.

A hash mismatch like the one that you observed can mean that the DLL and PDB were produced by different builds. Subsequent builds of the same code produce hashes that differ only by an embedded timestamp. Try checking if that might by an issue in your case.

**Comment by TripleEmcoder** [comment]
As there is not further info on this matter, and I do believe that hash generation is correct, I am going to go ahead and close this issue for now.
